### ISSUE TITLE
Asserts

### ISSUE THREAD

**Issue by memee** [fantasyland/fantasy-laws#8]
https://github.com/fantasyland/fantasy-laws/blob/863bdee40a17e6ad3b474e176a1536eee4b32436/src/internal/assert.js#L9

This implementation rather disables [**tape**](https://www.npmjs.com/package/tape) users from asserting in the way **tape** lib requires. Like having test plan: `t.plan(1)` where you declare the number of asserts.

Example:
```
var test = require('tape');
 
test('timing test', function (t) {
    t.plan(2); // <--- plan
    
    t.equal(typeof Date.now, 'function'); // <--- assert
    var start = Date.now();
    
    setTimeout(function () {
        t.equal(Date.now() - start, 100); // <--- assert
    }, 100);
});
```
No idea come to my mind that will not turn the implementation upside down.
Any idea of workarounds that will help to use other test frameworks than Mocha?

**Comment by davidchambers** [comment]
I'm not familiar with tape, @memee. I'll be happy to consider a proposal to restructure the assertion thunks in order to improve interoperability.

**Comment by safareli** [comment]
I think you can just nut call the plan and use `t.end()` when test ends

**Comment by safareli** [comment]
i have actually done that and works fine https://github.com/safareli/free/blob/master/test/laws.js#L22

**Comment by davidchambers** [comment]
That's good to know. Thanks, Irakli. :)

**Comment by safareli** [comment]
You are welcome!
